[profile.release]
panic = "unwind"

[patch.crates-io]
wasmi = { git = "https://github.com/patractlabs/wasmi", branch = "v0.6.2", optional = true }

[workspace]
members = [
    "bin/europa/",
    "bin/europa/cli",
    "bin/europa/rpc",
    "bin/europa/executor",
    "bin/europa/runtime",

    "client/api",
    "client/cli",
    "client/db",
    "client/executor",
    "client/service",
    "client/rpc",

    "primitives/sandbox"
]
exclude = [ "vendor/substrate" ]
