[profile.release]
panic = "unwind"

[patch.crates-io]
# patch for substrate crate

[workspace]
members = [
    "bin/europa/",
    "bin/europa/cli",
    "bin/europa/rpc",
    "bin/europa/executor",
    "bin/europa/runtime",

    "client/cli",
    "client/executor",
    "client/service",
    "client/rpc",
]
