[package]
name = "ec-service"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
parking_lot = "0.10.0"
codec = { package = "parity-scale-codec", version = "1.3.4" }
tracing = "0.1.19"
exit-future = "0.2.0"
log = "0.4.8"
#futures01 = { package = "futures", version = "0.1.29" }
futures = { version = "0.3.4", features = ["compat"] }

sp-runtime = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sp-consensus = { version = "0.8.0" }
sp-utils = { version = "2.0.0" }
sp-api = { version = "2.0.0" }
sp-core = { version = "2.0.0" }
sp-state-machine = { version = "0.8.0" }
sp-tracing = { version = "2.0.0" }
sp-externalities = { version = "0.8.0" }
sp-version = { version = "2.0.0" }

sc-block-builder = { version = "0.8.0" }
sc-client-api = { version = "2.0.0" }
sc-client-db = { version = "0.8.0" }
sc-service = { version = "0.8.0" }
sc-keystore = { version = "2.0.0" }

ec-executor = { path = "../executor" }
