[package]
name = "ec-service"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
parking_lot = "0.10.0"
codec = { package = "parity-scale-codec", version = "1.3.4" }
tracing = "0.1.19"

sp-runtime = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sp-consensus = { version = "0.8.0" }
sp-utils = { version = "2.0.0" }
sp-api = { version = "2.0.0" }
sp-core = { version = "2.0.0" }
sp-state-machine = { version = "0.8.0" }
sp-tracing = { version = "2.0.0" }

sc-block-builder = { version = "0.8.0" }
sc-client-api = { version = "2.0.0" }
