[package]
name = "ec-service"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
parking_lot = "0.10.0"
codec = { package = "parity-scale-codec", version = "1.3.4" }
tracing = "0.1.19"
exit-future = "0.2.0"
log = "0.4.8"
futures = { version = "0.3.4", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
jsonrpc-pubsub = "15.0"
jsonrpc-core = "15.0"
serde_json = "1.0"
hex = "0.4.0"

sp-runtime = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sp-consensus = { version = "0.8.0" }
sp-utils = { version = "2.0.0" }
sp-api = { version = "2.0.0" }
sp-core = { version = "2.0.0" }
sp-state-machine = { version = "0.8.0" }
sp-tracing = { version = "2.0.0" }
sp-externalities = { version = "0.8.0" }
sp-version = { version = "2.0.0" }
sp-inherents = { version = "2.0.0" }
sp-transaction-pool = { version = "2.0.0" }
sp-session = { version = "2.0.0" }
sp-trie = { version = "2.0.0" }

sc-block-builder = { version = "0.8.0" }
sc-client-api = { version = "2.0.0" }
sc-client-db = { version = "0.8.0" }
sc-service = { version = "0.8.0" }
sc-keystore = { version = "2.0.0" }
sc-rpc-server = { version = "2.0.0" }
sc-rpc = { version = "2.0.0" }
sc-transaction-pool = { version = "2.0.0" }
sc-consensus = { version = "0.8.0" }
sc-consensus-manual-seal = { version = "0.8.0" }
sc-basic-authorship = { version = "0.8.0" }
sc-chain-spec = { version = "2.0.0" }
sc-tracing = { version = "2.0.0" }
sc-informant = { version = "0.8.0" }

ec-executor = { path = "../executor" }
ec-client-db = { path = "../db" }
ec-client-api = { path = "../api" }
ec-rpc = { path = "../rpc" }
