[package]
name = "europa-executor"
version = "0.2.1"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
ec-executor = { path = "../../../client/executor" }
europa-runtime = { path = "../runtime" }
