[package]
name = "executor"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
sc-executor = { version = "0.8.0" }
europa-runtime = { path = "../runtime" }
