[package]
name = "ep-extensions"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
sp-externalities = { version = "0.9.0", git = "https://github.com/paritytech/substrate.git", branch = "master" }
