[package]
name = "europa-rpc"
version = "0.2.1"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"

sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-keystore = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-epochs = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }

substrate-frame-rpc-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

# vendor
pallet-contracts-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

europa-runtime = { path = "../runtime" }

