[package]
name = "europa-rpc"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"

sc-client-api = { version = "2.0.0" }
sc-rpc = { version = "2.0.0" }

sp-api = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }
sp-transaction-pool = { version = "2.0.0" }
sc-keystore = { version = "2.0.0" }
sp-blockchain = { version = "2.0.0" }
sc-rpc-api = { version = "0.8.0" }
sp-block-builder = { version = "2.0.0" }
sp-consensus = { version = "0.8.0" }
sc-consensus-epochs = { version = "0.8.0" }

substrate-frame-rpc-system = { version = "2.0.0" }
pallet-transaction-payment-rpc = { version = "2.0.0" }
#pallet-contracts-rpc = { version = "0.8.0" }

europa-runtime = { path = "../runtime" }

