[package]
name = "europa-cli"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
serde_json = "1.0"

sp-consensus = { version = "0.8.0" }
sp-inherents = { version = "2.0.0" }
sp-timestamp = { version = "2.0.0" }
sp-core = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }

sc-cli = { version = "0.8.0" }
sc-transaction-pool = { version = "2.0.0" }
sc-consensus = { version = "0.8.0" }
sc-consensus-manual-seal = { version = "0.8.0" }
sc-basic-authorship = { version = "0.8.0" }

ec-service = { path = "../../../client/service" }
ec-cli = { path = "../../../client/cli" }

pallet-contracts = { version = "2.0.0" }

europa-runtime = { path = "../runtime" }
europa-executor = { path = "../executor" }
europa-rpc = { path = "../rpc" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0" }
