[package]
name = "europa-cli"
version = "0.2.1"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
serde_json = "1.0"

sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-manual-seal = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }

ec-service = { path = "../../../client/service" }
ec-cli = { path = "../../../client/cli" }

# vendor
pallet-contracts = { version = "3.0.0", path = "../../../vendor/substrate/frame/contracts" }

europa-runtime = { path = "../runtime" }
europa-executor = { path = "../executor" }
europa-rpc = { path = "../rpc" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
