[package]
name = "europa-cli"
version = "0.4.0-dev"
authors = ["Patract Labs <https://github.com/patractlabs>"]
edition = "2021"
license = "GPL-3.0"

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }

[dependencies]
clap = { version = "3.1", features = ["derive"] }
serde_json = "1.0"

# Substrate
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.21" }

# Europa
ec-cli = { path = "../../../client/cli" }
ec-service = { path = "../../../client/service" }
europa-executor = { path = "../executor" }
europa-rpc = { path = "../rpc" }
europa-runtime = { path = "../runtime" }
